# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Heading.create(id: 1, heading_text: 'Other Code Challenge Websites')
Heading.create(id: 2, heading_text: 'Skills In Demand')
Heading.create(id: 3, heading_text: 'Web Developer Pay Rates')
Heading.create(id: 4, heading_text: 'Advice on Finding a Job')
Heading.create(id: 5, heading_text: 'Improving Your Resumé')
Heading.create(id: 6, heading_text: 'Building Your Portfolio')
Heading.create(id: 7, heading_text: 'Preparing for Interviews')
Heading.create(id: 8, heading_text: 'Data Structures, Algorithms & Big-O Notation')
Heading.create(id: 9, heading_text: 'Example Interview Questions')
Heading.create(id: 10, heading_text: 'Helpful YouTube Channels')
Heading.create(id: 11, heading_text: 'Remote/International Jobs')
Heading.create(id: 12, heading_text: 'Job Opportunities in the United States')
Heading.create(id: 13, heading_text: 'Job Opportunities in the United Kingdom')
Heading.create(id: 14, heading_text: 'Job Opportunities in Canada')
Heading.create(id: 15, heading_text: 'Job Opportunities in Australia')
Heading.create(id: 16, heading_text: 'Job Opportunities in New Zealand')
Heading.create(id: 17, heading_text: 'Overview of Advanced Course Options')
Heading.create(id: 18, heading_text: 'Cryptocurrency')
Heading.create(id: 19, heading_text: 'Cyber Security')
Heading.create(id: 20, heading_text: 'Data Science')
Heading.create(id: 21, heading_text: 'Machine Learning')
Heading.create(id: 22, heading_text: 'Mobile Apps')
Heading.create(id: 23, heading_text: 'UX and UI')

Link.create(heading_id: '1', title: 'Medium: The 10 Best Coding Challenge Websites for 2018', URL: 'https://medium.com/coderbyte/the-10-best-coding-challenge-websites-for-2018-12b57645b654/')
Link.create(heading_id: '1', title: 'CodeCondo: 17 Coding Challenges to Help You Train Your Brain', URL: 'https://codecondo.com/coding-challenges/')

Link.create(heading_id: '2', title: '15 of the highest-paying tech jobs to consider in 2024', URL: 'https://www.betterup.com/blog/best-paying-jobs-in-technology')
Link.create(heading_id: '2', title: 'The top 10 in-demand tech jobs in 2024', URL: 'https://www.hays.com/career-advice/article/top-10-in-demand-tech-jobs-in-2024')
Link.create(heading_id: '2', title: 'The 10 most in-demand tech skills in 2024', URL: 'https://www.pluralsight.com/resources/blog/it-ops/top-tech-skills-2024-with-tests')
Link.create(heading_id: '2', title: '7 most in-demand programming languages for 2024', URL: 'https://thenextweb.com/news/7-most-in-demand-programming-languages-2024')
Link.create(heading_id: '2', title: 'Most in Demand Programming Languages [2024]', URL: 'https://medium.com/@codeavail/most-in-demand-programming-languages-2024-3ef8c4baa22e')
Link.create(heading_id: '2', title: 'Top 10 Best Programming Languages to Learn in 2024', URL: 'https://www.geeksforgeeks.org/best-programming-languages/')
Link.create(heading_id: '2', title: 'Get Hired as a Developer: Learn Multiple Languages', URL: 'https://www.switchup.org/blog/get-hired-as-a-developer-learn-multiple-programming-languages')

Link.create(heading_id: '3', title: 'What Web Developer Salary To Expect?', URL: 'https://careerfoundry.com/en/blog/web-development/how-much-will-i-earn-as-a-web-developer/')
Link.create(heading_id: '3', title: 'How Much Will I Earn as a Full-Stack Developer in 2024?', URL: 'https://careerfoundry.com/en/blog/web-development/full-stack-developer-salary-guide/')
Link.create(heading_id: '3', title: 'Web developer salary in United States', URL: 'https://www.indeed.com/career/web-developer/salaries')
Link.create(heading_id: '3', title: 'Web Developer average salary in United Kingdom, 2024', URL: 'https://uk.talent.com/salary?job=Web+Developer')
Link.create(heading_id: '3', title: 'Web Developer Salaries in United Kingdom', URL: 'https://www.glassdoor.co.uk/Salaries/web-developer-salary-SRCH_KO0,13.htm')
Link.create(heading_id: '3', title: 'Web Developer Salaries in Canada', URL: 'https://www.glassdoor.ca/Salaries/web-developer-salary-SRCH_KO0,13.htm')
Link.create(heading_id: '3', title: 'Web Developer Salary in Australia', URL: 'https://au.jobted.com/salary/web-developer')

Link.create(heading_id: '4', title: '“5 Things You Must Do to Land a Web Development Job” (YouTube)', URL: 'https://www.youtube.com/watch?v=y-Sy4mnMBrs')
Link.create(heading_id: '4', title: '“How to Land Your First Development Job in 5 Simple Steps”', URL: 'https://medium.com/javascript-scene/how-to-land-your-first-development-job-in-5-simple-steps-4e9fb73314c')
Link.create(heading_id: '4', title: '“The Tools and Resources that Landed Me a Front-End Developer Job”', URL: 'https://medium.freecodecamp.org/the-tools-and-resources-that-landed-me-a-front-end-developer-job-1314c6f1fa7f')
Link.create(heading_id: '4', title: '“I Spent 3 Months Applying to Jobs After a Coding Bootcamp. Here’s What I Learned.”', URL: 'https://medium.freecodecamp.org/5-key-learnings-from-the-post-bootcamp-job-search-9a07468d2331')
Link.create(heading_id: '4', title: '7 Ways to Turn Your New Coding Skills Into a New Job', URL: 'https://www.themuse.com/advice/7-ways-to-turn-your-new-coding-skills-into-a-new-job')
Link.create(heading_id: '4', title: 'What to do After Your Coding Bootcamp', URL: 'https://www.karllhughes.com/posts/graduate-code-bootcamp')

Link.create(heading_id: '5', title: 'Web Developer Resumé: Sample & Complete Guide', URL: 'https://zety.com/blog/web-developer-resume')
Link.create(heading_id: '5', title: 'My Perfect Resumé: Web Developer Resumé Sample', URL: 'https://www.myperfectresume.com/how-to/technology/web-developer-resume-sample/')
Link.create(heading_id: '5', title: 'LiveCareer: IT Web Developer Resumé Example', URL: 'https://www.livecareer.com/resumes/examples/it/web-developer')
Link.create(heading_id: '5', title: 'Web Developer Resumé With Summary Statement Example', URL: 'https://www.thebalancecareers.com/web-developer-resume-with-summary-statement-example-2063275')
Link.create(heading_id: '5', title: 'Monster: Web Developer Resumé Sample', URL: 'https://www.monster.com/career-advice/article/web-developer-resume-sample')
Link.create(heading_id: '5', title: '7 Creative Ways to Greatly Improve Your Resumé', URL: 'https://www.lifehack.org/articles/work/7-creative-ways-greatly-improve-resume.html')

Link.create(heading_id: '6', title: 'SwitchUp: A Guide to Developing Your Programming Portfolio', URL: 'https://www.switchup.org/blog/a-guide-to-developing-your-programming-portfolio')
Link.create(heading_id: '6', title: 'SitePoint: How to Create a Portfolio Site That Will Get You Hired', URL: 'https://www.sitepoint.com/how-to-create-a-portfolio-site-that-will-get-you-hired/')
Link.create(heading_id: '6', title: 'CodeMentor: 12 Things Web Developers Must Include in Their Portfolios', URL: 'https://www.codementor.io/learn-programming/12-important-things-to-include-in-web-dev-portfolios')
Link.create(heading_id: '6', title: 'Grok Code: The Power of a Programming Portfolio', URL: 'https://www.grokcode.com/58/the-power-of-a-programming-portfolio/')
Link.create(heading_id: '6', title: 'SwitchUp: UX Design Portfolio Advice From Christine Yeh', URL: 'https://www.switchup.org/blog/ux-design-q-a-with-springboard')
Link.create(heading_id: '6', title: 'Coding Horror: A Programmer’s Portfolio', URL: 'https://blog.codinghorror.com/a-programmers-portfolio/')

Link.create(heading_id: '7', title: 'Reddit: Here’s How to Prepare for Tech Interviews', URL: 'https://www.reddit.com/r/cscareerquestions/comments/1jov24/heres_how_to_prepare_for_tech_interviews/')
Link.create(heading_id: '7', title: 'CodeMentor: How to Impress in a Junior Developer Job Interview', URL: 'https://www.codementor.io/learn-programming/junior-developer-interview-tips-to-success')
Link.create(heading_id: '7', title: 'Quora: How Should I Prepare for a Junior Software Developer Interview?', URL: 'https://www.quora.com/How-should-I-prepare-for-a-junior-software-developer-interview')

Link.create(heading_id: '8', title: 'What are the Most Important Data Structure and Algorithms to Prepare for Google Interview?', URL: 'https://www.quora.com/What-are-the-most-important-data-structure-and-algorithms-to-prepare-for-Google-Interview')
Link.create(heading_id: '8', title: 'GitHub: Tech Interview Cheat Sheet', URL: 'https://gist.github.com/TSiege/cbb0507082bb18ff7e4b')
Link.create(heading_id: '8', title: '10 Common Data Structures Explained with Videos + Exercises', URL: 'https://medium.freecodecamp.org/10-common-data-structures-explained-with-videos-exercises-aaff6c06fb2b')
Link.create(heading_id: '8', title: 'Book: Think Data Structures', URL: 'http://greenteapress.com/wp/think-data-structures/')

Link.create(heading_id: '9', title: 'FullStack Café: 50 Junior Web Developer Interview Questions (And Answers)', URL: 'https://www.fullstack.cafe/blog/50-junior-web-developer-interview%20-questions-and-answers-ultimate-list-2018')
Link.create(heading_id: '9', title: 'Github: Front-end Job Interview Questions', URL: 'https://github.com/h5bp/Front-end-Developer-Interview-Questions')
Link.create(heading_id: '9', title: 'Top 50 Data Structure Interview Questions & Answers', URL: 'https://career.guru99.com/top-50-data-structure-interview-questions/')
Link.create(heading_id: '9', title: 'Interview Questions for Software Developers', URL: 'https://www.geeksforgeeks.org/interview-preparation-for-software-developer/')
Link.create(heading_id: '9', title: 'CoderByte: Coding Challenges and Interview Prep', URL: 'https://www.coderbyte.com/')
Link.create(heading_id: '9', title: 'Interview Cake (Sample questions at bottom of page)', URL: 'https://www.interviewcake.com/')
Link.create(heading_id: '9', title: 'CareerCup: Sample Interview Questions', URL: 'https://careercup.com/')

Link.create(heading_id: '10', title: 'Super Simple Dev (Simon Bao)', URL: 'https://www.youtube.com/@SuperSimpleDev/videos')
Link.create(heading_id: '10', title: 'Web Dev Simplified', URL: 'https://www.youtube.com/@WebDevSimplified/videos')
Link.create(heading_id: '10', title: 'Stefan Mischook', URL: 'https://www.youtube.com/@StefanMischook/videos')
Link.create(heading_id: '10', title: 'Colt Steele', URL: 'https://www.youtube.com/@ColtSteeleCode/videos')
Link.create(heading_id: '10', title: 'Code with Ania Kubów', URL: 'https://www.youtube.com/@AniaKubow/videos')
Link.create(heading_id: '10', title: 'James Q Quick', URL: 'https://www.youtube.com/@JamesQQuick/videos')
Link.create(heading_id: '10', title: 'Forrest Knight', URL: 'https://www.youtube.com/@fknight/videos')

Link.create(heading_id: '11', title: 'WellFound: “Start-up job search”', URL: 'https://wellfound.com/')
Link.create(heading_id: '11', title: 'We Work Remotely', URL: 'https://weworkremotely.com')
Link.create(heading_id: '11', title: 'Awesome Remote Job: List of Awesome Remote Working Resources', URL: 'https://github.com/lukasz-madon/awesome-remote-job')
Link.create(heading_id: '11', title: 'Wikipedia: List of Employment Websites', URL: 'https://en.wikipedia.org/wiki/List_of_employment_websites')

Link.create(heading_id: '12', title: 'Indeed', URL: 'https://www.indeed.com/')
Link.create(heading_id: '12', title: 'Monster', URL: 'https://www.monster.com/')
Link.create(heading_id: '12', title: 'Dice', URL: 'https://www.dice.com/')
Link.create(heading_id: '12', title: 'Hired', URL: 'https://hired.com/')
Link.create(heading_id: '12', title: 'GlassDoor', URL: 'https://www.glassdoor.com/index.htm')
Link.create(heading_id: '12', title: 'CareerBuilder', URL: 'https://www.careerbuilder.com/')
Link.create(heading_id: '12', title: 'ZipRecruiter', URL: 'https://www.ziprecruiter.com/')
Link.create(heading_id: '12', title: 'SimplyHired', URL: 'https://www.simplyhired.com/')
Link.create(heading_id: '12', title: 'Snag A Job', URL: 'https://www.snagajob.com/')
Link.create(heading_id: '12', title: 'CareerJet', URL: 'https://www.careerjet.com/')
Link.create(heading_id: '12', title: 'LinkUp', URL: 'https://linkup.com/')

Link.create(heading_id: '13', title: 'Indeed', URL: 'https://uk.indeed.com/')
Link.create(heading_id: '13', title: 'Reed', URL: 'https://reed.co.uk/')
Link.create(heading_id: '13', title: 'Adecco', URL: 'https://www.adecco.co.uk/')
Link.create(heading_id: '13', title: 'CW Jobs', URL: 'https://www.cwjobs.co.uk/')
Link.create(heading_id: '13', title: 'Jobsite', URL: 'https://www.jobsite.co.uk/')
Link.create(heading_id: '13', title: 'Monster', URL: 'https://www.monster.co.uk/')
Link.create(heading_id: '13', title: 'Hired', URL: 'https://hired.co.uk/')
Link.create(heading_id: '13', title: 'TechnoJobs', URL: 'https://www.technojobs.co.uk/')
Link.create(heading_id: '13', title: 'TotalJobs', URL: 'https://www.totaljobs.co.uk/')
Link.create(heading_id: '13', title: 'GlassDoor', URL: 'https://www.glassdoor.co.uk/')

Link.create(heading_id: '14', title: 'Indeed', URL: 'https://ca.indeed.com/')
Link.create(heading_id: '14', title: 'JobBoom', URL: 'https://www.jobboom.com/en/')
Link.create(heading_id: '14', title: 'Monster', URL: 'https://www.monster.ca/')
Link.create(heading_id: '14', title: 'Workopolis', URL: 'https://www.workopolis.com/')
Link.create(heading_id: '14', title: 'JobRapido', URL: 'https://ca.jobrapido.com/')
Link.create(heading_id: '14', title: 'JobBank', URL: 'https://www.jobbank.gc.ca/')

Link.create(heading_id: '15', title: 'JobSearch', URL: 'http://www.jobsearch.com.au')
Link.create(heading_id: '15', title: 'Indeed', URL: 'https://au.indeed.com/')
Link.create(heading_id: '15', title: 'CareerOne', URL: 'https://www.careerone.com.au/')
Link.create(heading_id: '15', title: 'Seek', URL: 'https://www.seek.com.au/')
Link.create(heading_id: '15', title: 'CareerJet', URL: 'https://www.careerjet.com.au/')
Link.create(heading_id: '15', title: 'Adzuna', URL: 'https://www.adzuna.com.au/')
Link.create(heading_id: '15', title: 'GumTree', URL: 'https://www.gumtree.com.au/jobs/')

Link.create(heading_id: '16', title: 'Jora', URL: 'https://nz.jora.com/')
Link.create(heading_id: '16', title: 'Seek', URL: 'https://www.seek.co.nz/')
Link.create(heading_id: '16', title: 'Indeed', URL: 'https://nz.indeed.com/')
Link.create(heading_id: '16', title: 'CareerJet', URL: 'https://www.careerjet.co.nz/')
Link.create(heading_id: '16', title: 'Adzuna', URL: 'https://www.adzuna.co.nz/')

Link.create(heading_id: '17', title: 'CIO: The 15 most in-demand tech jobs for 2024', URL: 'https://www.cio.com/article/230935/hiring-the-most-in-demand-tech-jobs-for-2021.html')
Link.create(heading_id: '17', title: 'The Top 10 Most In-Demand Skills For The Next 10 Years', URL: 'https://www.forbes.com/sites/bernardmarr/2022/08/22/the-top-10-most-in-demand-skills-for-the-next-10-years/')
Link.create(heading_id: '17', title: 'Tech Jobs in 2024: The Complete Guide', URL: 'https://careerfoundry.com/en/blog/career-change/tech-jobs/')

Link.create(heading_id: '18', title: 'What is Cryptocurrency? Everything You Need To Know!', URL: 'https://blockgeeks.com/guides/what-is-cryptocurrency/')
Link.create(heading_id: '18', title: 'What is Cryptocurrency? Guide for Beginners', URL: 'https://cointelegraph.com/bitcoin-for-beginners/what-are-cryptocurrencies#future-of-cryptocurrency')
Link.create(heading_id: '18', title: 'What Skills Are Needed for Cryptocurrency Jobs?', URL: 'https://coincentral.com/skills-cryptocurrency-jobs/')
Link.create(heading_id: '18', title: '13 Cryptocurrency Careers (With Salary Info and Duties)', URL: 'https://www.indeed.com/career-advice/finding-a-job/crypto-currency-careers')
Link.create(heading_id: '18', title: 'SwitchUp: Best Cryptocurrency Courses and Bootcamps', URL: 'https://www.switchup.org/subjects/how-to-learn-cryptocurrency')

Link.create(heading_id: '19', title: 'Cisco: What is Cyber Security?', URL: 'https://www.cisco.com/c/en/us/products/security/what-is-cybersecurity.html')
Link.create(heading_id: '19', title: 'Trellix: What is Cyber Security?', URL: 'https://www.trellix.com/security-awareness/cybersecurity/what-is-cybersecurity/')
Link.create(heading_id: '19', title: 'What Skills Do You Need for a High-Paying Cyber Security Job?', URL: 'https://news.clearancejobs.com/2016/11/12/skills-need-high-paying-cyber-security-job/')
Link.create(heading_id: '19', title: 'The Skills Required for a Career in Cyber Security', URL: 'https://www.cybersecurityjobs.net/the-skills-required-for-a-career-in-cyber-security/')
Link.create(heading_id: '19', title: 'SwitchUp: 2023 Best Cyber Security Bootcamps', URL: 'https://www.switchup.org/rankings/best-cyber-security-bootcamps')

Link.create(heading_id: '20', title: 'Thinkful: What is Data Science?', URL: 'https://www.thinkful.com/blog/what-is-data-science/')
Link.create(heading_id: '20', title: 'SwitchUp: Astronomy Helped by Data Science', URL: 'https://www.switchup.org/blog/thinkful-astronomy-data-science')
Link.create(heading_id: '20', title: 'SwitchUp: Data Analyst vs. Data Scientist: What’s the Difference?', URL: 'https://www.switchup.org/blog/data-analyst-vs-data-scientist')
Link.create(heading_id: '20', title: 'Udacity: 8 Skills You Need to Be a Data Scientist', URL: 'https://blog.udacity.com/2014/11/data-science-job-skills.html')
Link.create(heading_id: '20', title: 'What are the Skills Needed to Become a Data Scientist in 2018?', URL: 'https://towardsdatascience.com/what-are-the-skills-needed-to-become-a-data-scientist-in-2018-d037012f1db2/')
Link.create(heading_id: '20', title: 'How to Get a Data Science Job', URL: 'https://www.dataquest.io/blog/how-to-get-a-data-science-job/')
Link.create(heading_id: '20', title: 'GitHub: How Do I Get My First Data Science Job?', URL: 'https://reshamas.github.io/first-data-science-job/')
Link.create(heading_id: '20', title: 'SwitchUp: 2023 Best Data Science Bootcamps', URL: 'https://www.switchup.org/rankings/best-data-science-bootcamps')

Link.create(heading_id: '21', title: 'TechRadar: What is Machine Learning?', URL: 'https://www.techradar.com/news/what-is-machine-learning/')
Link.create(heading_id: '21', title: 'Udacity: 5 Skills You Need to Become a Machine Learning Engineer', URL: 'https://blog.udacity.com/2016/04/5-skills-you-need-to-become-a-machine-learning-engineer.html')
Link.create(heading_id: '21', title: 'MindMajix: Skills Required for Machine Learning Jobs', URL: 'https://mindmajix.com/what-skills-needed-for-machine-learning-jobs/')
Link.create(heading_id: '21', title: 'Skills You Need to Land a Machine Learning Job', URL: 'https://www.itcareerfinder.com/brain-food/blog/entry/skills-you-need-to-land-a-machine-learning-job.html')
Link.create(heading_id: '21', title: 'Quora: How Do I get a Machine Learning Job?', URL: 'https://www.quora.com/How-do-I-get-into-a-machine-learning-job/')
Link.create(heading_id: '21', title: 'SwitchUp: Best Machine Learning Courses and Bootcamps', URL: 'https://www.switchup.org/subjects/how-to-learn-machine-learning')

Link.create(heading_id: '22', title: 'Overview of the Mobile App Development Process (Infographic)', URL: 'https://www.techinasia.com/talk/complete-overview-mobile-app-development-process-infographic/')
Link.create(heading_id: '22', title: 'The Mobile App Development Process', URL: 'https://thebhwgroup.com/blog/mobile-app-development-process/')
Link.create(heading_id: '22', title: '7 Skills You Need to Be an iOS Developer', URL: 'https://blog.udacity.com/2016/02/7-skills-you-need-to-be-an-ios-developer.html')
Link.create(heading_id: '22', title: '8 “Must Have” Skills in an Android App Developer', URL: 'https://www.keyideasinfotech.com/blog/8-must-have-skill-in-an-android-app-developer/')
Link.create(heading_id: '22', title: 'How to Become a Mobile App Developer', URL: 'https://www.businessnewsdaily.com/10756-how-to-become-a-mobile-app-developer.html')
Link.create(heading_id: '22', title: 'SwitchUp: Best Courses and Bootcamps for Mobile Apps', URL: 'https://www.switchup.org/subjects/how-to-learn-mobile/')

Link.create(heading_id: '23', title: 'Career Foundry: The Difference Between UX and UI Design - A Layman’s Guide', URL: 'https://careerfoundry.com/en/blog/ux-design/the-difference-between-ux-and-ui-design-a-laymans-guide/')
Link.create(heading_id: '23', title: 'UI vs. UX: What’s the difference between user interface and user experience?', URL: 'https://www.usertesting.com/blog/ui-vs-ux/')
Link.create(heading_id: '23', title: 'Career Foundry: The Need-To-Know Skills Of User Experience And User Interface Design', URL: 'https://careerfoundry.com/en/blog/ux-design/required-skills-for-ux-ui-design/')
Link.create(heading_id: '23', title: 'Medium: 10 must have skills for UX designers', URL: 'https://uxplanet.org/10-must-have-skills-for-ux-designers-8ce53c30d4ee')
Link.create(heading_id: '23', title: 'UX Beginner: How to Get a UX Job with No Professional UX Experience', URL: 'https://www.uxbeginner.com/how-to-get-a-ux-job-with-no-professional-ux-experience/')
Link.create(heading_id: '23', title: 'Silicon Republic: Expert tips on how to get a job in UX or UI', URL: 'https://www.siliconrepublic.com/advice/ui-ux-jobs-career-advice-harvey-nash')
Link.create(heading_id: '23', title: 'SwitchUp: Best UI Design Courses and Bootcamps', URL: 'https://www.switchup.org/subjects/how-to-learn-ui-design/')
Link.create(heading_id: '23', title: 'SwitchUp: Best UX Courses and Bootcamps', URL: 'https://www.switchup.org/subjects/how-to-learn-ux/')
